Условие задания 1

Создайте массив NumPy размером 3х3, содержащий числа от 1 до 9. Умножьте
все элементы массива на 2, а затем замените все элементы больше 10 на 0.
Выведите итоговый массив.

In [2]:
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr = arr * 2
arr[arr > 10] = 0
print(arr)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


Условие задания 2

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и
выведите все элементы, которые делятся на 5 без остатка. Затем замените их на
-1 и выведите обновленный массив.

In [3]:
arr = np.random.randint(1, 101, 20)
print("Исходный массив:")
print(arr)
print("\nЧисла, делящиеся на 5:")
print(arr[arr % 5 == 0])
arr[arr % 5 == 0] = -1
print("\nОбновленный массив:")
print(arr)

Исходный массив:
[100  50  90  50   1  31  43   7  72  82  57   7  55  98  95   9  68  85
  24   9]

Числа, делящиеся на 5:
[100  50  90  50  55  95  85]

Обновленный массив:
[-1 -1 -1 -1  1 31 43  7 72 82 57  7 -1 98 -1  9 68 -1 24  9]


Условие задания 3

Создайте два массива NumPy размером 1х5, заполненные случайными числами
от 0 до 50.

Объедините эти массивы в один двумерный массив (по строкам).
Разделите полученный массив на два массива, каждый из которых содержит 5
элементов.

Выведите все промежуточные и итоговые результаты.

In [4]:
a = np.random.randint(0, 51, 5)
b = np.random.randint(0, 51, 5)
print("Массив A:", a)
print("Массив B:", b)
c = np.vstack((a, b))
print("\nОбъединенный массив:")
print(c)
a_new, b_new = np.vsplit(c, 2)
print("\nРазделенный массив A:")
print(a_new.flatten())
print("Разделенный массив B:")
print(b_new.flatten())

Массив A: [35 28 41 46 44]
Массив B: [47 30  3 27 45]

Объединенный массив:
[[35 28 41 46 44]
 [47 30  3 27 45]]

Разделенный массив A:
[35 28 41 46 44]
Разделенный массив B:
[47 30  3 27 45]


Условие задания 4

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10.
Вычислите сумму всех элементов, сумму положительных элементов и сумму
отрицательных элементов. Выведите результаты.

In [6]:
arr = np.linspace(-10, 10, 50)
print("Массив:")
print(arr)
sum_all = np.sum(arr)
sum_pos = np.sum(arr[arr > 0])
sum_neg = np.sum(arr[arr < 0])
print("\nСумма всех элементов:", sum_all)
print("Сумма положительных элементов:", sum_pos)
print("Сумма отрицательных элементов:", sum_neg)

Массив:
[-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]

Сумма всех элементов: 7.105427357601002e-15
Сумма положительных элементов: 127.55102040816328
Сумма отрицательных элементов: -127.55102040816327


Условие задания 5

Создайте:

· Единичную матрицу размером 4х4.  
· Диагональную матрицу размером 4х4 с диагональными элементами [5, 10, 15,
20] (не использовать циклы).

Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [7]:
I = np.eye(4)
D = np.diag([5, 10, 15, 20])
sum_I = I.sum()
sum_D = D.sum()
print(I)
print(D)
print("Сумма элементов единичной матрицы:", sum_I)
print("Сумма элементов диагональной матрицы:", sum_D)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма элементов единичной матрицы: 4.0
Сумма элементов диагональной матрицы: 50


Условие задания 6

Создайте две квадратные матрицы NumPy размером 3х3, заполненные
случайными целыми числами от 1 до 20. Вычислите и выведите: их сумму, их разность, их поэлементное произведение.

In [8]:
A = np.random.randint(1, 21, (3, 3))
B = np.random.randint(1, 21, (3, 3))

print("A:\n", A)
print("\nB:\n", B)

print("\nСумма:\n", A + B)
print("\nРазность:\n", A - B)
print("\nПоэлементное произведение:\n", A * B)

A:
 [[18  6  2]
 [17  4  1]
 [15 19 11]]

B:
 [[ 2 11  6]
 [ 7  7  5]
 [ 3  1 14]]

Сумма:
 [[20 17  8]
 [24 11  6]
 [18 20 25]]

Разность:
 [[16 -5 -4]
 [10 -3 -4]
 [12 18 -3]]

Поэлементное произведение:
 [[ 36  66  12]
 [119  28   5]
 [ 45  19 154]]


Условие задания 7

Создайте две матрицы NumPy:

· Первую размером 2х3, заполненную случайными числами от 1 до 10.   
· Вторую размером 3х2, заполненную случайными числами от 1 до 10.  

Выполните матричное умножение (@ или np.dot ) и выведите результат.

In [9]:
A = np.random.randint(1, 11, (2, 3))
B = np.random.randint(1, 11, (3, 2))

print("Матрица A:\n", A)
print("\nМатрица B:\n", B)

C = A @ B
print("\nРезультат умножения:\n", C)
C = np.dot(A, B)
print("\nРезультат умножения:\n", C)

Матрица A:
 [[1 3 7]
 [6 3 3]]

Матрица B:
 [[9 2]
 [9 3]
 [8 1]]

Результат умножения:
 [[ 92  18]
 [105  24]]

Результат умножения:
 [[ 92  18]
 [105  24]]


Условие задания 8

Создайте случайную квадратную матрицу 3х3. Найдите и выведите:

· Определитель этой матрицы  
· Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена)  

Используйте функции np.linalg.det и np.linalg.inv.

In [10]:
A = np.random.randint(1, 11, (3, 3))
print("Матрица A:\n", A)
det = np.linalg.det(A)
print("\nОпределитель:", det)

if det != 0:
    inv_A = np.linalg.inv(A)
    print("\nОбратная матрица:\n", inv_A)
else:
    print("\nМатрица вырождена (обратной матрицы не существует)")

Матрица A:
 [[ 6  7  3]
 [ 3  1 10]
 [ 5  9  4]]

Определитель: -184.00000000000006

Обратная матрица:
 [[ 0.4673913   0.00543478 -0.36413043]
 [-0.20652174 -0.04891304  0.27717391]
 [-0.11956522  0.10326087  0.08152174]]


Условие задания 9

Создайте матрицу NumPy размером 4х4, содержащую случайные целые числа от
1 до 50. Выведите:

· Исходную матрицу  
· Транспонированную матрицу  
· След матрицы (сумму элементов на главной диагонали)  

Используйте np.trace для нахождения следа.

In [11]:
A = np.random.randint(1, 51, (4, 4))
print("Исходная матрица:\n", A)
print("\nТранспонированная матрица:\n", A.T)
trace = np.trace(A)
print("\nСлед матрицы:", trace)

Исходная матрица:
 [[36 16 50 45]
 [ 4 36 36 15]
 [26 40 24 43]
 [38  9 44 39]]

Транспонированная матрица:
 [[36  4 26 38]
 [16 36 40  9]
 [50 36 24 44]
 [45 15 43 39]]

След матрицы: 135


Условие задания 10

Решите систему линейных уравнений вида:

$$
\begin{cases}
2x + 3y - z = 5 \\
4x - y + 2z = 6 \\
-3x + 5y + 4z = -2
\end{cases}
$$   

Используйте матричное представление Ах = В , где А - матрица коэффициентов,
х - вектор неизвестных, В - вектор правой части. Решите систему с помощью
np.linalg.solve и выведите результат.

In [12]:
A = np.array([
    [2, 3, -1],
    [4, -1, 2],
    [-3, 5, 4]
])
B = np.array([5, 6, -2])
X = np.linalg.solve(A, B)
print("Решение системы:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])

Решение системы:
x = 1.6396396396396398
y = 0.5765765765765767
z = 0.009009009009008993


Условие задачи 11 по варианту 12

Продажа билетов. На концерт продано 500 билетов трех категорий:
стандартные, премиум и VIP. Билеты премиум стоят в 1.5 раза дороже
стандартных, а VIP - в 2 раза дороже премиум. Общий доход от продажи
составил 600 000 рублей. Сколько билетов каждого типа было продано, если
известно, что стандартных билетов было на 100 больше, чем премиум?

In [13]:
A = np.array([
    [1, 1, 1],
    [1, -1, 0],
    [1, 1.5, 3]
])
B = np.array([500, 100, 600])
X = np.linalg.solve(A, B)

print("Стандартные:", int(X[0]))
print("Премиум:", int(X[1]))
print("VIP:", int(X[2]))

Стандартные: 300
Премиум: 200
VIP: 0
